version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

volumes:
  keycloak_data:
